# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trag.proto\x12\x08myrag.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x99\x01\n\x0b\x43hatRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x35\n\x11\x63urrent_timestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\t\n\x01k\x18\x03 \x01(\x05\x12\x12\n\nsession_id\x18\x04 \x01(\t\x12\x0f\n\x07user_id\x18\x05 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x06 \x01(\t\"Z\n\x0c\x43hatResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x10\n\x08is_final\x18\x02 \x01(\x08\x12)\n\x07sources\x18\x03 \x03(\x0b\x32\x18.myrag.v1.SourceDocument\";\n\x0eSourceDocument\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0b\n\x03uri\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x02\"F\n\x15IndexDocumentsRequest\x12\x17\n\x0f\x64rive_folder_id\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x02 \x01(\t\"M\n\x16IndexDocumentsResponse\x12\x13\n\x0b\x63hunk_count\x18\x01 \x01(\x05\x12\r\n\x05\x66iles\x18\x02 \x03(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2\x9a\x01\n\nRagService\x12\x37\n\x04\x43hat\x12\x15.myrag.v1.ChatRequest\x1a\x16.myrag.v1.ChatResponse0\x01\x12S\n\x0eIndexDocuments\x12\x1f.myrag.v1.IndexDocumentsRequest\x1a .myrag.v1.IndexDocumentsResponseB$\n me.clauminirockpt.myrag_proto.v1P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n me.clauminirockpt.myrag_proto.v1P\001'
  _globals['_CHATREQUEST']._serialized_start=57
  _globals['_CHATREQUEST']._serialized_end=210
  _globals['_CHATRESPONSE']._serialized_start=212
  _globals['_CHATRESPONSE']._serialized_end=302
  _globals['_SOURCEDOCUMENT']._serialized_start=304
  _globals['_SOURCEDOCUMENT']._serialized_end=363
  _globals['_INDEXDOCUMENTSREQUEST']._serialized_start=365
  _globals['_INDEXDOCUMENTSREQUEST']._serialized_end=435
  _globals['_INDEXDOCUMENTSRESPONSE']._serialized_start=437
  _globals['_INDEXDOCUMENTSRESPONSE']._serialized_end=514
  _globals['_RAGSERVICE']._serialized_start=517
  _globals['_RAGSERVICE']._serialized_end=671
# @@protoc_insertion_point(module_scope)
