# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rag_pb2 as rag__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rag_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RagServiceStub(object):
    """RAG 검색 + 문서 인덱싱 서비스
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_stream(
                '/myrag.v1.RagService/Chat',
                request_serializer=rag__pb2.ChatRequest.SerializeToString,
                response_deserializer=rag__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.IndexDocuments = channel.unary_unary(
                '/myrag.v1.RagService/IndexDocuments',
                request_serializer=rag__pb2.IndexDocumentsRequest.SerializeToString,
                response_deserializer=rag__pb2.IndexDocumentsResponse.FromString,
                _registered_method=True)


class RagServiceServicer(object):
    """RAG 검색 + 문서 인덱싱 서비스
    """

    def Chat(self, request, context):
        """질문에 대해 토큰 단위로 스트리밍 응답
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IndexDocuments(self, request, context):
        """Google Drive 문서 인덱싱 트리거
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RagServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=rag__pb2.ChatRequest.FromString,
                    response_serializer=rag__pb2.ChatResponse.SerializeToString,
            ),
            'IndexDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.IndexDocuments,
                    request_deserializer=rag__pb2.IndexDocumentsRequest.FromString,
                    response_serializer=rag__pb2.IndexDocumentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myrag.v1.RagService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('myrag.v1.RagService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RagService(object):
    """RAG 검색 + 문서 인덱싱 서비스
    """

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/myrag.v1.RagService/Chat',
            rag__pb2.ChatRequest.SerializeToString,
            rag__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IndexDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myrag.v1.RagService/IndexDocuments',
            rag__pb2.IndexDocumentsRequest.SerializeToString,
            rag__pb2.IndexDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
